# version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "8001:8000"
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1
    env_file:
      - .env
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
