version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "8001:8000"
    env_file:
      - .env
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,api.justcheckinghow.com